In [11]:
# 1. Compute the multiplication of the following matrices:

In [12]:
import numpy as np

A = np.array([[1, 0],
              [0, 1]])
B = np.array([[1, 2],
              [3, 4]])

C = A @ B          
print(C)

[[1 2]
 [3 4]]


In [13]:
# 2. Generate an array of length 3n filled with the cyclic pattern 1, 2, 3.

In [14]:
def cyclic_123(n):
    base = np.array([1, 2, 3])
    return np.tile(base, n)

print(cyclic_123(4))  

[1 2 3 1 2 3 1 2 3 1 2 3]


In [15]:
# 3. Create a 10×10 matrix of zeros and then "frame" it with a border of ones.

In [16]:
M = np.zeros((10, 10), dtype=int)
M[0, :] = 1
M[-1, :] = 1
M[:, 0] = 1
M[:, -1] = 1
print(M)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [17]:
# 4. Create a random 3×5 array using the np.random.rand(3, 5) function and compute: the sum of all the entries, the sum of the rows and the sum of the columns. (many Numpy functions have an optional axis= argument!)

In [18]:
X = np.random.rand(3, 5)

total_sum = X.sum()
row_sums = X.sum(axis=1)
col_sums = X.sum(axis=0)

print(total_sum)
print(row_sums)
print(col_sums)

8.042849753649266
[2.59981355 2.75642472 2.68661148]
[1.3722728  1.44399056 1.76129783 2.40837221 1.05691635]


In [19]:
# 5. Given the following arrays representing logical values (0 = False, 1 = True) compute the logical AND and logical OR operations for every pair of values of the two arrays: [1, 1, 0, 0] [1, 0, 1, 0] Hint: you may need to set the data type (dtype) of the array's elements to 'bool'

In [20]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

and_result = np.logical_and(a, b)
or_result  = np.logical_or(a, b)

print(and_result)
print(or_result)

[ True False False False]
[ True  True  True False]


In [21]:
# 6. Find indices of non-zero elements from [1, 2, 0, 0, 4, 0]

In [23]:
x = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(x)[0]
print(indices)     

[0 1 4]


In [24]:
# 7. Create a 8×8 array with random values and find minimum and maximum value

In [25]:
Y = np.random.rand(8, 8)
min_val = Y.min()
max_val = Y.max()
print(min_val, max_val)

0.010312871748784036 0.9767906554372024


In [26]:
# 8. Create a 8×8 array with random natural values from the range (1-100) on the diagonal, other values should be 0. Hint: You can use numpy's 'eye' function.

In [28]:
diag_vals = np.random.randint(1, 101, size=8)
D = np.diag(diag_vals)   
print(D)

[[30  0  0  0  0  0  0  0]
 [ 0 28  0  0  0  0  0  0]
 [ 0  0 87  0  0  0  0  0]
 [ 0  0  0 98  0  0  0  0]
 [ 0  0  0  0 64  0  0  0]
 [ 0  0  0  0  0 53  0  0]
 [ 0  0  0  0  0  0 25  0]
 [ 0  0  0  0  0  0  0 39]]


In [29]:
# 9. Write a function which creates an n×n matrix with (i,j)-entry equal to i+j.

In [30]:
def ij_sum_matrix(n):
    i = np.arange(n).reshape(-1, 1)
    j = np.arange(n).reshape(1, -1)
    return i + j

print(ij_sum_matrix(4))

[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


In [31]:
# 10. Write a function which creates an n×n matrix with rows having subsequent values multiplied by the row's number. For example for n = 4:

In [33]:
def row_scaled_matrix(n):
    base = np.arange(n)         
    rows = np.arange(1, n+1).reshape(-1, 1)  
    return rows * base

print(row_scaled_matrix(4))

[[ 0  1  2  3]
 [ 0  2  4  6]
 [ 0  3  6  9]
 [ 0  4  8 12]]
